student_number=int(input("Enter your student number: "))
student_name = input("Enter your name: ")
math = int(input("Enter your math marks: "))
science = int(input("Enter your science marks: "))
english = int(input("Enter your english marks: "))
average=round((math+science+english)/3,2)
print("Student Details:")
print("Student Number:", student_number)
print("Name:", student_name)
print("Math Marks:", math)
print("Science Marks:", science)
print("English Marks:", english)
print("Average Marks:", average)